### ISSUE TITLE
Basic sample

### ISSUE THREAD

**Issue by julienvedebe** [lautarobock/inversify-agenda#3]
Hi,

I'm quite new with inversify witch look fantastik, I used many times agendaJS and this module should fit my need.
However I started writing some task and a config file but i'm not sure how to correctly bind tasks.
Could you please provide a sample for a quick init of things ?

Many thanks

**Comment by julienvedebe** [comment]
Sorry I found my issue, I did bind the class containing my task in the inversify config (after container creating).
After debugging I see an ambiguous name so I guess that my class was binded two times.

After search I found that task decorator bind class so I don't need to do it after container creation.

So for now I only import my class before the creation of the container like this  

import { Container } from 'inversify';
import '../tasks/processReports';

const container = new Container();
export default container;

Don't feel so confident about this way of doing so if you have time to add a sample will be great 

Thanks

**Comment by lautarobock** [comment]
sorry, I've just seen this message, I dont know why were notified by email. Give me a while and I will push an example of use.

**Comment by lautarobock** [comment]
@julienvedebe 
Here you have a very simple working example. 
https://github.com/lautarobock/inversify-agenda/blob/master/examples/simple/README.md
Please let me know if it is enough or you need something else

**Comment by julienvedebe** [comment]
@lautarobock thanks for help my mistake was to bind task and not just importing, it's working correctly.
